### ISSUE TITLE
Missing Tutorial regarding utilities package

### ISSUE THREAD

**Issue by ah2190** [cubicoder/cubicoder.github.io#6]
I've been trying my best to follow these tutorials, but there's something missing from them - that being that the cubicoder.tutorialmod.util package in the 1.12 tutorials isn't explained in how one makes it so that items can be added. In fact, there's also broken links in the tutorials.md file as well, which also doesn't include the proxy link.

**Comment by cubicoder** [comment]
The `cubicoder.tutorialmod.util` isn’t mentioned directly, but it is stated in the First Item tutorial that a utility class could be made which automatically names an item. A possible implementation of that is given in the `RegistryUtil` class, located in `cubicoder.tutorialmod.util`. However, it was intentionally left up to the reader to try and devise their own way, or to look at the code for an answer.

As to the links, which ones are broken for you? I checked all of them on the site and they seemed fine to me. If you were trying to follow them here in GitHub, it doesn’t work, but on the actual site it works fine. If there are broken links, I’ll get them fixed ASAP; just want to know which ones to look at.

Also, I left out the proxy tutorial on the site because it was not necessary for anything else covered in the tutorial series, and I didn’t want to confuse anyone.

**Comment by ah2190** [comment]
Ah. I see. Yeah, I was trying to follow them here on the GitHub. On the site, they all work as intended, so that's not an issue in that case. In any case, I managed to get things sorted out with my own project, although now I've gone beyond what the tutorial would give now.

Might as well close this then as it works, and is understandable why that stuff isn't on the site.
